# Generated by Django 5.0.7 on 2024-09-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_listingid_bid_userid_comment_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listingId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
        ),
    ]
